gantt
    title 標準的な博士後期課程の3年間（四半期 x 12）
    dateFormat  YYYY-MM
    section 1年目
    核となる論文1の研究→論文投稿    :active, 2020-04, 365d
    第1四半期           :2020-04, 90d
    第2四半期           :2020-07, 90d
    第3四半期           :2020-10, 90d
    第4四半期           :2021-01, 90d
    section 2年目
    核となる論文1の査読修正→採録    :active, 2021-04, 365d
    核となる論文2の研究→論文投稿    :active, 2021-04, 365d
    第1四半期           :2021-04, 90d
    第2四半期           :2021-07, 90d
    第3四半期           :2021-10, 90d
    第4四半期           :2022-01, 90d
    section 3年目
    核となる論文2の査読修正→採録    :active, 2022-04, 180d
    博士論文執筆        :active, 2022-04, 180d
    第1四半期           :2022-04, 90d
    第2四半期           :2022-07, 90d
    論文審査～学位授与   :active, 2022-10, 180d
    第3四半期           :2022-10, 90d
    第4四半期           :2023-01, 90d
